eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@mc-discovery:8761/eureka
spring:
  application:
    name: product
  data:
    mongodb:
      database: products
      host: mc-mongo-product
      port: 27017
server:
  port: 8081
