eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3307/order
    password: '123456789'
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    template:
      default-topic: orderPlaceTopic
    consumer:
      group-id: orderPlaceId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.microcommerce.order.domain.event.OrderPlacedEvent
    bootstrap-servers: localhost:9092



server:
  port: 8083