eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@mc-discovery:8761/eureka
spring:
  kafka:
    bootstrap-servers: mc-broker:9092
mc-redis:
  host: mc-redis
  port: 6379
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
server:
  port: 0